FROM ubuntu:latest

LABEL Maintainer="James Poulin"

# Set noninteractive mode for apt-get
ENV DEBIAN_FRONTEND noninteractive

# Update
RUN apt-get update

# Install package here for cache
RUN apt-get -y install postfix nano less

COPY deploy.sh /

RUN chmod +x /launch.sh

ENTRYPOINT ["/launch.sh"]

CMD ["postfix", "start-fg"]
